services:
  cid-docs:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  cid-docs-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    command: npm start
    profiles:
      - dev

# BUILD USING: docker-compose build cid-docs
# RUN USING: docker-compose up -d cid-docs
